version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    container_name: "backend"
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
    env_file:
      - ./env/backend.env
  mongo:
    image: "mongo"

    container_name: "mongodb"

    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo-volume:/data/db

    command: mongod --auth

    env_file:
      - ./env/mongo.env
