# Use an official Node.js runtime as the base image
FROM node:14

# Create a working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install Node.js dependencies
RUN npm install

# Copy all application files to the working directory
COPY . .

# Expose port 3000 (adjust as needed)
EXPOSE 3000

# Define the startup command for your Express.js application
CMD ["npm", "run", "dev"]
